# NumPy Arrays

In [1]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.random.rand(5,5)

array([[0.17001984, 0.92475178, 0.41915713, 0.3452122 , 0.13345103],
       [0.64670598, 0.98280908, 0.99715005, 0.4884896 , 0.36023067],
       [0.89142415, 0.93673529, 0.96880712, 0.70524852, 0.22322854],
       [0.01604036, 0.75482771, 0.35599115, 0.3064059 , 0.10100186],
       [0.90335804, 0.17152686, 0.76911647, 0.77276478, 0.79196669]])

In [19]:
np.random.randn(2)

array([ 1.1191045 , -0.36843532])

In [33]:
np.random.randint(1, 100, 10)

array([41, 75, 24, 94, 53, 52, 54, 26, 86, 21])

In [34]:
arr1 = np.arange(25)

In [35]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr1 = np.random.randint(0, 50, 10)

In [37]:
ranarr1

array([ 6,  4, 22, 42, 31, 45, 44, 34, 20, 37])

In [39]:
arr1.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
# In order for the reshape method, we need the product of the two arguments to be equal to the number of elements in the array.
ranarr1.reshape(2, 5)

array([[ 6,  4, 22, 42, 31],
       [45, 44, 34, 20, 37]])

In [43]:
ranarr1.max() #Returns the max value in the array

45

In [44]:
ranarr1.argmax() # Returns the index of the max value in the array.

5

In [45]:
ranarr1.argmin()

1

In [51]:
arr1.shape

(25,)

In [55]:
arr1 = arr1.reshape(5, 5)

In [56]:
arr1.shape

(5, 5)

In [57]:
arr1.dtype # Returns the data type that is the array

dtype('int32')